name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov selenium
        pip install -r requirements.txt
    
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('vader_lexicon')"
    
    - name: Setup Chrome and WebDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: latest
    
    - name: Run tests without Selenium
      run: |
        python -m pytest coursework2/tests/ -v -k "not selenium"
    
    - name: Run Selenium tests
      run: |
        # Start Chrome in background
        google-chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 &
        # Run only Selenium tests
        python -m pytest coursework2/tests/ -v -m selenium
    
    - name: Generate coverage report
      run: |
        python -m pytest coursework2/tests/ --cov=coursework2 --cov-report=xml
      if: success()
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      if: success()