name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
    
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('vader_lexicon')"
    
    - name: Run tests with pytest
      run: |
        python -m pytest coursework2/tests/
    
    - name: Generate coverage report
      run: |
        python -m pytest coursework2/tests/ --cov=coursework2 --cov-report=xml
      if: success()
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      if: success()